# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-apple-darwin" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
yanked = "allow" # "deny" # TODO: Re-enable when possible.

ignore = [
  "RUSTSEC-2021-0127", # serde_cbor

  # The following dependencies come in through ssi crate.
  # See https://github.com/spruceid/ssi/issues/599 and
  # https://github.com/scouten-adobe/cawg-identity-core/issues/29.
  "RUSTSEC-2021-0139", # ansi_term (unmaintained)
  "RUSTSEC-2021-0145", # atty (unaligned read, possibly unmaintained)
  "RUSTSEC-2021-0141", # dotenv (meant for dev/testing only)
  "RUSTSEC-2023-0055", # lexical 6.1.1 (soundness issues)
  "RUSTSEC-2022-0040", # owning_ref 0.4.1 (soundness issues, unmaintained)
  "RUSTSEC-2023-0071", # rsa 0.6.1 (Marvin key recovery attack)
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "allow" # "deny" # TODO: Re-enable when possible.
wildcards = "allow"

# List of allowed licenses.
[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "LicenseRef-ring",
  "MIT",
  "MPL-2.0",
  "Unicode-DFS-2016",
  "W3C-20150513", # needs review
  "Zlib",
]
confidence-threshold = 0.9

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
  { path = "LICENSE", hash = 3171872035 }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
